### ISSUE TITLE
[Bug]: RobotCommandHandle crashes when mode_request_cb() is called with missing robot_name/fleet_name

### ISSUE THREAD

**Issue by DoppiaEffe94** [open-rmf/rmf_demos#253] opened 2024-07-26 14:01 UTC
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

Ubuntu 22.04

### Open-RMF installation type

Source build

### Open-RMF version or commit hash

70b79e25a094ae00e4a75a04593d063823cf3c15

### ROS distribution

Humble

### ROS installation type

Binaries

### Description of the bug

In the RobotCommandHandle.py, `mode_request_cb()` is the callback of the subscriber to the topic `/action_execution_notice`.
This cb function is supposed to check if the fleet_name or robot_name have a value.
However, in python3, this verification is done with the `not ...` operation.

### Steps to reproduce the bug

1. Send a message to the topic `/action_execution_notice` without robot_name or fleet_name.

### Expected behavior

The mode_request_cb() function should return without crashing.

### Actual behavior

The mode_request_cb() function crashes whenever the step one of the described field is called.

**Comment by xiyuoh** [comment] 2024-08-08 03:00
Hello @DoppiaEffe94 ! Thanks for bringing this up and opening the PR for it. I've tried your steps to reproduce the bug in Office world (22.04 + Humble binaries + RMF source build) but I can't seem to replicate it.

If an empty `fleet_name` is provided, the message would be ignored as `""` is not the fleet name (second condition in [this line](https://github.com/open-rmf/rmf_demos/blob/humble/rmf_demos_fleet_adapter/rmf_demos_fleet_adapter/RobotCommandHandle.py#L724)). If an empty `robot_name` is provided, the message would be accepted and the action is marked as finished successfully.

However, I think it is very reasonable to check for a `not ...`  over a `is None` to rule out empty strings.

Additionally, as I was testing this I've found a relevant bug, which is the lack of a `robot_name` filter inside this `mode_request_cb`. If the action is performed by `tinyRobot2` and I send a message to `/action_execution_notice` and populate it with `robot_name: tinyRobot1`, it would end `tinyRobot2`'s action as well.

To follow up on this issue, may I request for 2 things:
1. If your `mode_request_cb()` is still crashing, could you provide some logs so that I can try to reproduce the problem? Preferably with a link to a gist. This is so that we can check if there are other underlying issues causing the crash.
2. Could you update your PR to add in a filter for `robot_name`, i.e. return if `msg.robot_name != self.name` since it is a relevant part of the code?

**Comment by DoppiaEffe94** [comment] 2024-08-09 19:50
Hey @xiyuoh !

Thank you for testing it, but apparently I was neither clear myself about what was the crashing issue.

I tested the code further and I found out the reason for the code to not working properly.
Apparently, I wouldn't need to provide you some logs because:

- If `fleet_name` is empty, it returns as expected. **However**, this is not caused by `msg.fleet_name is None` but by `msg.fleet_name != self.fleet_name`. You can easily test it yourself by removing the condition `msg.fleet_name != self.fleet_name` and sending an empty `fleet_name` field. You can assume that `msg.fleet_name is None` is not doing its job.

> Could you update your PR to add in a filter for robot_name, i.e. return if msg.robot_name != self.name since it is a relevant part of the code?
I updated the PR as you suggested.

Let me know if you need anything else or I was not clear.

Thank you!

**Comment by xiyuoh** [comment] 2024-08-12 01:22
Hey @DoppiaEffe94 just to clarify, when we send a ROS 2 message with an empty string field, it will be populated with a `""` rather than a `None`, so it was intended to filter out empty fleet names with `msg.fleet_name != self.fleet_name`.

May I do a final check with you: without the PR, is your program still crashing when given an empty **fleet name**? I understand if it crashed with an empty robot name since we've only just added a check for with `msg.robot_name != self.name`. Trying to make sure that there's no other source of crashes 😄

**Comment by DoppiaEffe94** [comment] 2024-08-12 14:46
Hello @xiyuoh !

> May I do a final check with you: without the PR, is your program still crashing when given an empty fleet name? I understand if it crashed with an empty robot name since we've only just added a check for with msg.robot_name != self.name. Trying to make sure that there's no other source of crashes 😄

I may confirm that is not crashing anymore for an empty **msg.fleet_name**, at least for what concerning this part of the code :D

Thank you for the support!

**Comment by xiyuoh** [comment] 2024-08-12 15:08
Awesome! Thanks for spotting the bug! Closing as PR for the fix has been merged.

**Closed by xiyuoh** 2024-08-12 15:08 UTC
Labels: bug
