### ISSUE TITLE
[Other issue]:  Is there a detailed and comprehensive tutorial for integrating real robots?

### ISSUE THREAD

**Issue by lmmir** [open-rmf/rmf_demos#270] opened 2024-12-05 01:19 UTC
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

Is there a detailed and comprehensive tutorial for integrating real robots?

**Comment by akash-roboticist** [comment] 2024-12-05 01:31
Closing, duplicate of https://github.com/open-rmf/rmf/discussions/569

**Closed by akash-roboticist** 2024-12-05 01:31 UTC
